package localdata

import "backend/models"

type CardInfoData interface {
	GetAll() []models.CardInfo
}

type cardInfoData struct {
	items []models.CardInfo
}

func InitCardInfoData() CardInfoData {
	return &cardInfoData{
		items: []models.CardInfo{
			{
				Type:     "job",
				JobClass: "adRow",
				JobTitle: "Nomad Insurance by SafetyWing",
				Company:  "Global health coverage for remote worker and nomads",
				LogoType: "image",
				Logo:     "/images/logo-biz-0.png",
			},
			{
				Type:        "job",
				JobClass:    "job1",
				CardVariant: "normal",
				LogoType:    "image",
				Logo:        "/images/logo-biz-1.webp",
				JobTitle:    "Junior Crypto Analyst & Trader",
				Company:     "ELEMENT TERRA",
				Location:    "🌏 Worldwide",
				Salary:      "💰 $50k - $70k",
				Schedule:    "⏰ Part time",
				New:         false,
				Verify:      true,
				Label:       []string{"Other", "Crypto", "Finance"},
				Date:        "19d",
			},
			{
				Type:        "job",
				JobClass:    "job1",
				CardVariant: "expand",
				LogoType:    "text",
				LogoText:    "GP",
				JobTitle:    "Senior Amazon Brand Manager",
				Company:     "GNO Parnters",
				Location:    "🌏 Worldwide",
				Salary:      "💰 $220k - $300k",
				New:         true,
				Verify:      true,
				BalloonIcon: true,
				Label:       []string{"Marketing", "Sales"},
				Date:        "7d",
				Details: &models.CardDetails{
					JobDescription: "<p><strong><u>Senior Amazon Brand Manager - GNO Partners</u></strong></p><p>GNO Partners was founded by Gal and Ouriel, who built and exited two successful Amazon brands. We help Amazon FBA sellers scale profitably using our proven system.</p><p>We are a Done With You consultancy, meaning we don't manage client accounts, we set the strategy, analyze their brand, and teach them how to execute using our resources.</p><p class=\"p-strong\"><strong><u>Why Join Us?</u></strong></p><ul><li>Fully remote Amazon consulting agency.</li><li>High-performance culture: hard work, speed, over-delivery, and trust.</li><li><strong>Competitive Compensation: Total OTE of $220,000-$300,000+.</strong><ul style=\"margin: 0;\"><li>Base Salary: $120,000</li><li>Performance-Based Earnings: Realistically getting an extra $180,000 per year based on performance, and more (no cap).</li></ul></li><li>Work with a team that <strong>lives and breathes Amazon</strong> while having fun doing it.</li></ul><p class=\"p-strong\"><strong><u>Who We’re Looking For:</u></strong></p><p>We are seeking a Senior Amazon Brand Manager who deeply understands Amazon FBA, enjoys strategizing for brand growth, and can tackle complex challenges with <strong>precision and speed.</strong></p><p class=\"p-strong\"><strong><u>Key Skills & Experience:</u></strong></p><ul><li><strong>Organic Ranking Mastery:</strong> Product launches, ranking strategies, and algorithm insights.</li><li><strong>Amazon PPC Expertise:</strong> Strategy + execution, proven hands on experience managing minimum <strong>$50K+/mo budgets.</strong></li><li><strong>Brand Management:</strong> Experience managing Private Label brands generating a minimum of $10M in annual revenue</li><li><strong>Logistics & Backend:</strong> Strong grasp of <strong>COGs, fees, inventory, and profitability (P&L) optimization.</strong></li><li><strong>Amazon Catalog Troubleshooter:</strong> Proven expertise in diagnosing and resolving complex catalog issues.</li></ul><p class=\"p-strong\"><strong><u>Responsibilities</u></strong></p><ul><li>Lead weekly strategy calls with clients, ensuring project progress.</li><li>Solve Amazon challenges and guide clients through key projects.</li><li>Track progress and provide clear next steps.</li><li>Offer daily support via Slack & Email.</li><li>Continuously improve our consulting systems.</li><li>Attend weekly training and team meetings.</li></ul><p class=\"p-strong\"><strong><u>Qualifications:</u></strong></p><ul><li>Full-time, remote.</li><li><strong>3+ years Amazon FBA experience</strong>, managing brands <strong>$10M+ in revenue minimum.</strong></li><li><strong>PPC expertise:</strong> Managed <strong>$50k monthly ad budgets minimum.</strong></li><li><strong>Seller Central pro:</strong> Navigate and optimize quickly.</li><li>Strong project management & client communication skills.</li><li>Positive, proactive, and <strong>client-focused</strong> personality.</li><li><strong>Fluent in English.</strong></li><li>Ambitious and driven, with a relentless work ethic to maximize earning potential</li></ul><p>If you're an Amazon expert, you're driven, strategic, and thrive in high-growth environments, we want you on our team!</p><p style=\"font-style: italic;\">*For referrals, email us at HR @ gnopartners.com and CC the candidate you’re introducing.</p><p>Please mention the word <strong>REDEEM</strong> when applying to show you read the job post completely (#RNDkuMTU2LjQxLjIyMg==). This is a feature to avoid fake spam applicants. Companies can search these words to find applicants that read this and instantly see they're human.</p>",
					WebsiteURL:     "elementalterra.com",
					QRCode:         "/images/qrcode.png",
				},
			},
			{
				Type:        "job",
				JobClass:    "job2",
				CardVariant: "normal",
				LogoType:    "image",
				Logo:        "/images/logo-biz-2.webp",
				JobTitle:    "STILL HIRING Virtual Assistant $1k Weekly Pay",
				Company:     "Lance Bridges Estimate and Quotation Company DBA Best Estimate Pro",
				Location:    "us United States",
				Salary:      "💰 $90k - $140k",
				Schedule:    "⏰ Part time",
				New:         false,
				Verify:      false,
				Label:       []string{"Sales", "Marketing", "Admin"},
				Date:        "27d",
			},
			{
				Type:        "job",
				JobClass:    "job2",
				CardVariant: "normal",
				LogoType:    "image",
				Logo:        "/images/logo-biz-3.webp",
				JobTitle:    "Senior Marketing Manager Paid Ads",
				Company:     "Acebet.com",
				Location:    "🌏 Worldwide",
				Salary:      "💰 $200k - $500k",
				New:         false,
				Verify:      false,
				BalloonIcon: true,
				Label:       []string{"Marketing"},
				Date:        "4d",
			},
			{
				Type:        "job",
				JobClass:    "job2",
				CardVariant: "normal",
				LogoType:    "image",
				Logo:        "/images/logo-biz-4.webp",
				JobTitle:    "Software Engineer C",
				Company:     "Octo Horizon",
				Location:    "🌏 Worldwide",
				Salary:      "💰 $120k - $180k",
				New:         true,
				Verify:      true,
				BalloonIcon: true,
				Label:       []string{"Engineer", "Technical", "Cloud"},
				Date:        "4h",
			},
			{
				Type:          "ad",
				JobClass:      "adReview",
				AdTitle:       "Unlock your remote career potential with Remote OK Premium",
				AdDescription: "Get exclusive access and be the first to apply to <strong>100,000+ remote jobs</strong> from <strong>10,000+ top companies</strong>  and land your dream remote position!",
				AdImage:       "/images/ad-pic.avif",
			},
			{
				Type:        "job",
				JobClass:    "job3",
				CardVariant: "normal",
				LogoType:    "image",
				Logo:        "/images/logo-biz-6.webp",
				JobTitle:    "Talent Acquisition Partner",
				Company:     "vCluster Labs",
				Location:    "🌏 Worldwide",
				Salary:      "💰 $120k - $180k",
				New:         true,
				Verify:      false,
				BalloonIcon: false,
				Label:       []string{"Engineer", "Architect", "Technical"},
				Date:        "3h",
			},
			{
				Type:        "job",
				JobClass:    "job3",
				CardVariant: "normal",
				LogoType:    "image",
				Logo:        "/images/logo-biz-5.webp",
				JobTitle:    "Vice President of Engagement Transformation",
				Company:     "Solera Health",
				Location:    "🌏 Probably Worldwide",
				Salary:      "💰 Upgrade to Premium to see...",
				New:         true,
				Verify:      false,
				BalloonIcon: false,
				Label:       []string{"Consultant", "Architect", "Technical"},
				Date:        "11h",
			},
			{
				Type:        "job",
				JobClass:    "job3",
				CardVariant: "normal",
				LogoType:    "image",
				Logo:        "/images/logo-biz-7.webp",
				JobTitle:    "Director AI Engineering",
				Company:     "Latern",
				Location:    "USA",
				Salary:      "💰 Upgrade to Premium to see...",
				New:         true,
				Verify:      false,
				BalloonIcon: false,
				Label:       []string{"Director", "Content", "Engineering"},
				Date:        "11h",
			},
			{
				Type:        "job",
				JobClass:    "job3",
				CardVariant: "normal",
				LogoType:    "image",
				Logo:        "/images/logo-biz-8.webp",
				JobTitle:    "Full Stack Software Engineer II",
				Company:     "Technergetics",
				Salary:      "💰 Upgrade to Premium to see...",
				New:         true,
				Verify:      false,
				BalloonIcon: false,
				Label:       []string{"Software", "HR", "System"},
				Date:        "11h",
			},
			{
				Type:        "job",
				JobClass:    "job3",
				CardVariant: "normal",
				LogoType:    "image",
				Logo:        "/images/logo-biz-9.webp",
				JobTitle:    "Senior Product Manager Platform Life Sciences",
				Company:     "SciLeads",
				Location:    "🌏 Probably Worldwide",
				Salary:      "💰 Upgrade to Premium to see...",
				New:         true,
				Verify:      false,
				BalloonIcon: false,
				Label:       []string{"Manager", "Support", "Leader"},
				Date:        "11h",
			},
			{
				Type:        "job",
				JobClass:    "job3",
				CardVariant: "normal",
				LogoType:    "image",
				Logo:        "/images/logo-biz-10.webp",
				JobTitle:    "Customer Success Manager",
				Company:     "GoodTime",
				Salary:      "💰 Upgrade to Premium to see...",
				New:         true,
				Verify:      false,
				BalloonIcon: false,
				Label:       []string{"Manager", "Support", "Leader"},
				Date:        "11h",
			},
			{
				Type:        "job",
				JobClass:    "job2",
				CardVariant: "normal",
				LogoType:    "image",
				Logo:        "/images/logo-biz-11.webp",
				JobTitle:    "Software engineer",
				Company:     "GoodTime",
				Location:    "eu Europe",
				Salary:      "💰 $140k - $150k",
				New:         true,
				Verify:      false,
				BalloonIcon: true,
				Label:       []string{"Engineer", "Docker", "Redis"},
				Date:        "11h",
			},
		},
	}
}

func (c *cardInfoData) GetAll() []models.CardInfo {
	return c.items
}
