package localdata

import "backend/models"

type LocationData interface {
	GetAll() []models.LocationData
}

type locationData struct {
	items []models.LocationData
}

func InitLocationData() LocationData {
	return &locationData{
		items: []models.LocationData{
			{ID: 1, Type: "group", Location: "Regions"},
			{ID: 2, Type: "item", Location: "🌏 Worldwide"},
			{ID: 3, Type: "item", Location: "⛰️ North America"},
			{ID: 4, Type: "item", Location: "💃 Latin America"},
			{ID: 5, Type: "item", Location: "🇪🇺 Europe"},
			{ID: 6, Type: "item", Location: "🦁 Africa"},
			{ID: 7, Type: "item", Location: "🕌 Middle East"},
			{ID: 8, Type: "item", Location: "⛩ Asia"},
			{ID: 9, Type: "item", Location: "🌊 Oceania"},
			{ID: 10, Type: "group", Location: "Countries"},
			{ID: 11, Type: "item", Location: "🇺🇸 United States"},
			{ID: 12, Type: "item", Location: "🇨🇦 Canada"},
			{ID: 13, Type: "item", Location: "🇬🇧 United Kingdom"},
			{ID: 14, Type: "item", Location: "🇦🇺 Australia"},
			{ID: 15, Type: "item", Location: "🇳🇿 New Zealand"},
			{ID: 16, Type: "item", Location: "🇮🇳 India"},
			{ID: 17, Type: "item", Location: "🇵🇹 Portugal"},
			{ID: 18, Type: "item", Location: "🇩🇪 Germany"},
			{ID: 19, Type: "item", Location: "🇳🇱 Netherlands"},
			{ID: 20, Type: "item", Location: "🇸🇬 Singapore"},
			{ID: 21, Type: "item", Location: "🇫🇷 France"},
			{ID: 22, Type: "item", Location: "🇭🇰 Hong Kong"},
			{ID: 23, Type: "item", Location: "🇧🇷 Brazil"},
			{ID: 24, Type: "item", Location: "🇬🇷 Greece"},
			{ID: 25, Type: "item", Location: "🇦🇪 United Arab Emirates"},
			{ID: 26, Type: "item", Location: "🇸🇪 Sweden"},
			{ID: 27, Type: "item", Location: "🇵🇱 Poland"},
			{ID: 28, Type: "item", Location: "🇪🇸 Spain"},
			{ID: 29, Type: "item", Location: "🇲🇽 Mexico"},
			{ID: 30, Type: "item", Location: "🇺🇦 Ukraine"},
			{ID: 31, Type: "item", Location: "🇯🇵 Japan"},
			{ID: 32, Type: "item", Location: "🇹🇭 Thailand"},
			{ID: 33, Type: "item", Location: "🇨🇿 Czechia"},
			{ID: 34, Type: "item", Location: "🇷🇺 Russia"},
			{ID: 35, Type: "item", Location: "🇮🇱 Israel"},
			{ID: 36, Type: "item", Location: "🇫🇮 Finland"},
			{ID: 37, Type: "item", Location: "🇨🇳 China"},
			{ID: 38, Type: "item", Location: "🇮🇩 Indonesia"},
			{ID: 39, Type: "item", Location: "🇦🇫 Afghanistan"},
			{ID: 40, Type: "item", Location: "🇦🇱 Albania"},
			{ID: 41, Type: "item", Location: "🇩🇿 Algeria"},
			{ID: 42, Type: "item", Location: "🇦🇸 American Samoa"},
			{ID: 43, Type: "item", Location: "🇦🇩 Andorra"},
			{ID: 44, Type: "item", Location: "🇦🇴 Angola"},
			{ID: 45, Type: "item", Location: "🇦🇮 Anguilla"},
			{ID: 46, Type: "item", Location: "🇦🇶 Antarctica"},
			{ID: 47, Type: "item", Location: "🇦🇬 Antigua and Barbuda"},
			{ID: 48, Type: "item", Location: "🇦🇷 Argentina"},
			{ID: 49, Type: "item", Location: "🇦🇲 Armenia"},
			{ID: 50, Type: "item", Location: "🇦🇼 Aruba"},
			{ID: 51, Type: "item", Location: "🇦🇹 Austria"},
			{ID: 52, Type: "item", Location: "🇦🇿 Azerbaijan"},
			{ID: 53, Type: "item", Location: "🇧🇸 The Bahamas"},
			{ID: 54, Type: "item", Location: "🇧🇭 Bahrain"},
			{ID: 55, Type: "item", Location: "🇧🇩 Bangladesh"},
			{ID: 56, Type: "item", Location: "🇧🇧 Barbados"},
			{ID: 57, Type: "item", Location: "🇧🇾 Belarus"},
			{ID: 58, Type: "item", Location: "🇧🇪 Belgium"},
			{ID: 59, Type: "item", Location: "🇧🇿 Belize"},
			{ID: 60, Type: "item", Location: "🇧🇯 Benin"},
			{ID: 61, Type: "item", Location: "🇧🇲 Bermuda"},
			{ID: 62, Type: "item", Location: "🇧🇹 Bhutan"},
			{ID: 63, Type: "item", Location: "🇧🇴 Bolivia"},
			{ID: 64, Type: "item", Location: "🇧🇦 Bosnia"},
			{ID: 65, Type: "item", Location: "🇧🇼 Botswana"},
			{ID: 66, Type: "item", Location: "🇧🇻 Bouvet Island"},
			{ID: 67, Type: "item", Location: "🇮🇴 British Indian Ocean Territory"},
			{ID: 68, Type: "item", Location: "🇧🇳 Brunei"},
			{ID: 69, Type: "item", Location: "🇧🇬 Bulgaria"},
			{ID: 70, Type: "item", Location: "🇧🇫 Burkina Faso"},
			{ID: 71, Type: "item", Location: "🇧🇮 Burundi"},
			{ID: 72, Type: "item", Location: "🇰🇭 Cambodia"},
			{ID: 73, Type: "item", Location: "🇨🇲 Cameroon"},
			{ID: 74, Type: "item", Location: "🇨🇻 Cape Verde"},
			{ID: 75, Type: "item", Location: "🇰🇾 Cayman Islands"},
			{ID: 76, Type: "item", Location: "🇨🇫 Central African Republic"},
			{ID: 77, Type: "item", Location: "🇹🇩 Chad"},
			{ID: 78, Type: "item", Location: "🇨🇱 Chile"},
			{ID: 79, Type: "item", Location: "🇨🇽 Christmas Island"},
			{ID: 80, Type: "item", Location: "🇨🇨 Cocos Islands"},
			{ID: 81, Type: "item", Location: "🇨🇴 Colombia"},
			{ID: 82, Type: "item", Location: "🇰🇲 Comoros"},
			{ID: 83, Type: "item", Location: "🇨🇬 Congo"},
			{ID: 84, Type: "item", Location: "🇨🇩 DR Congo"},
			{ID: 85, Type: "item", Location: "🇨🇰 Cook Islands"},
			{ID: 86, Type: "item", Location: "🇨🇷 Costa Rica"},
			{ID: 87, Type: "item", Location: "🇭🇷 Croatia"},
			{ID: 88, Type: "item", Location: "🇨🇺 Cuba"},
			{ID: 89, Type: "item", Location: "🇨🇼 Curaçao"},
			{ID: 90, Type: "item", Location: "🇨🇾 Cyprus"},
			{ID: 91, Type: "item", Location: "🇩🇰 Denmark"},
			{ID: 92, Type: "item", Location: "🇩🇯 Djibouti"},
			{ID: 93, Type: "item", Location: "🇩🇲 Dominica"},
			{ID: 94, Type: "item", Location: "🇩🇴 Dominican Republic"},
			{ID: 95, Type: "item", Location: "🇪🇨 Ecuador"},
			{ID: 96, Type: "item", Location: "🇪🇬 Egypt"},
			{ID: 97, Type: "item", Location: "🇸🇻 El Salvador"},
			{ID: 98, Type: "item", Location: "🇬🇶 Equatorial Guinea"},
			{ID: 99, Type: "item", Location: "🇪🇷 Eritrea"},
			{ID: 100, Type: "item", Location: "🇪🇪 Estonia"},
			{ID: 101, Type: "item", Location: "🇪🇹 Ethiopia"},
			{ID: 102, Type: "item", Location: "🇫🇰 Falkland Islands"},
			{ID: 103, Type: "item", Location: "🇫🇴 Faroe Islands"},
			{ID: 104, Type: "item", Location: "🇫🇯 Fiji"},
			{ID: 105, Type: "item", Location: "🇬🇫 French Guiana"},
			{ID: 106, Type: "item", Location: "🇹🇱 East Timor"},
			{ID: 107, Type: "item", Location: "🇹🇫 French Southern Territories"},
			{ID: 108, Type: "item", Location: "🇬🇦 Gabon"},
			{ID: 109, Type: "item", Location: "🇬🇲 Gambia"},
			{ID: 110, Type: "item", Location: "🇬🇪 Georgia"},
			{ID: 111, Type: "item", Location: "🇬🇭 Ghana"},
			{ID: 112, Type: "item", Location: "🇬🇮 Gibraltar"},
			{ID: 113, Type: "item", Location: "🇬🇱 Greenland"},
			{ID: 114, Type: "item", Location: "🇬🇩 Grenada"},
			{ID: 115, Type: "item", Location: "🇬🇵 Guadeloupe"},
			{ID: 116, Type: "item", Location: "🇬🇺 Guam"},
			{ID: 117, Type: "item", Location: "🇬🇹 Guatemala"},
			{ID: 118, Type: "item", Location: "🇬🇬 Guernsey"},
			{ID: 119, Type: "item", Location: "🇬🇳 Guinea"},
			{ID: 120, Type: "item", Location: "🇬🇼 Guinea Bissau"},
			{ID: 121, Type: "item", Location: "🇬🇾 Guyana"},
			{ID: 122, Type: "item", Location: "🇭🇹 Haiti"},
			{ID: 123, Type: "item", Location: "🇭🇲 Heard Island and McDonald Islands"},
			{ID: 124, Type: "item", Location: "🇭🇳 Honduras"},
			{ID: 125, Type: "item", Location: "🇭🇺 Hungary"},
			{ID: 126, Type: "item", Location: "🇮🇸 Iceland"},
			{ID: 127, Type: "item", Location: "🇮🇷 Iran"},
			{ID: 128, Type: "item", Location: "🇮🇶 Iraq"},
			{ID: 129, Type: "item", Location: "🇮🇪 Ireland"},
			{ID: 130, Type: "item", Location: "🇮🇲 Isle of Man"},
			{ID: 131, Type: "item", Location: "🇮🇹 Italy"},
			{ID: 132, Type: "item", Location: "🇨🇮 Cote d'Ivoire"},
			{ID: 133, Type: "item", Location: "🇯🇲 Jamaica"},
			{ID: 134, Type: "item", Location: "🇯🇪 Jersey"},
			{ID: 135, Type: "item", Location: "🇯🇴 Jordan"},
			{ID: 136, Type: "item", Location: "🇽🇰 Kosovo"},
			{ID: 137, Type: "item", Location: "🇽🇰 Kosovo"},
			{ID: 138, Type: "item", Location: "🇰🇿 Kazakhstan"},
			{ID: 139, Type: "item", Location: "🇰🇪 Kenya"},
			{ID: 140, Type: "item", Location: "🇰🇮 Kiribati"},
			{ID: 141, Type: "item", Location: "🇰🇵 North Korea"},
			{ID: 142, Type: "item", Location: "🇰🇷 South Korea"},
			{ID: 143, Type: "item", Location: "🏴 Kurdistan"},
			{ID: 144, Type: "item", Location: "🇰🇼 Kuwait"},
			{ID: 145, Type: "item", Location: "🇰🇬 Kyrgyzstan"},
			{ID: 146, Type: "item", Location: "🇱🇦 Laos"},
			{ID: 147, Type: "item", Location: "🇱🇻 Latvia"},
			{ID: 148, Type: "item", Location: "🇱🇧 Lebanon"},
			{ID: 149, Type: "item", Location: "🇱🇸 Lesotho"},
			{ID: 150, Type: "item", Location: "🇱🇷 Liberia"},
			{ID: 151, Type: "item", Location: "🇱🇾 Libya"},
			{ID: 152, Type: "item", Location: "🇱🇮 Liechtenstein"},
			{ID: 153, Type: "item", Location: "🇱🇹 Lithuania"},
			{ID: 154, Type: "item", Location: "🇱🇺 Luxembourg"},
			{ID: 155, Type: "item", Location: "🇲🇴 Macau"},
			{ID: 156, Type: "item", Location: "🇲🇰 North Macedonia"},
			{ID: 157, Type: "item", Location: "🇲🇬 Madagascar"},
			{ID: 158, Type: "item", Location: "🇲🇼 Malawi"},
			{ID: 159, Type: "item", Location: "🇲🇾 Malaysia"},
			{ID: 160, Type: "item", Location: "🇲🇻 Maldives"},
			{ID: 161, Type: "item", Location: "🇲🇱 Mali"},
			{ID: 162, Type: "item", Location: "🇲🇹 Malta"},
			{ID: 163, Type: "item", Location: "🇲🇭 Marshall Islands"},
			{ID: 164, Type: "item", Location: "🇲🇶 Martinique"},
			{ID: 165, Type: "item", Location: "🇲🇷 Mauritania"},
			{ID: 166, Type: "item", Location: "🇲🇺 Mauritius"},
			{ID: 167, Type: "item", Location: "🇾🇹 Mayotte"},
			{ID: 168, Type: "item", Location: "🇫🇲 Micronesia"},
			{ID: 169, Type: "item", Location: "🇲🇩 Moldova"},
			{ID: 170, Type: "item", Location: "🇲🇨 Monaco"},
			{ID: 171, Type: "item", Location: "🇲🇳 Mongolia"},
			{ID: 172, Type: "item", Location: "🇲🇪 Montenegro"},
			{ID: 173, Type: "item", Location: "🇲🇸 Montserrat"},
			{ID: 174, Type: "item", Location: "🇲🇦 Morocco"},
			{ID: 175, Type: "item", Location: "🇲🇿 Mozambique"},
			{ID: 176, Type: "item", Location: "🇲🇲 Myanmar"},
			{ID: 177, Type: "item", Location: "🇳🇦 Namibia"},
			{ID: 178, Type: "item", Location: "🇳🇷 Nauru"},
			{ID: 179, Type: "item", Location: "🇳🇵 Nepal"},
			{ID: 180, Type: "item", Location: "🇧🇶 Caribbean Netherlands"},
			{ID: 181, Type: "item", Location: "🇳🇨 New Caledonia"},
			{ID: 182, Type: "item", Location: "🇳🇮 Nicaragua"},
			{ID: 183, Type: "item", Location: "🇳🇪 Niger"},
			{ID: 184, Type: "item", Location: "🇳🇬 Nigeria"},
			{ID: 185, Type: "item", Location: "🇳🇺 Niue"},
			{ID: 186, Type: "item", Location: "🇳🇫 Norfolk Island"},
			{ID: 187, Type: "item", Location: "🇲🇵 Northern Mariana Islands"},
			{ID: 188, Type: "item", Location: "🇳🇴 Norway"},
			{ID: 189, Type: "item", Location: "🇴🇲 Oman"},
			{ID: 190, Type: "item", Location: "🇵🇸 Palestine"},
			{ID: 191, Type: "item", Location: "🇵🇰 Pakistan"},
			{ID: 192, Type: "item", Location: "🇵🇼 Palau"},
			{ID: 193, Type: "item", Location: "🇵🇦 Panama"},
			{ID: 194, Type: "item", Location: "🇵🇬 Papua New Guinea"},
			{ID: 195, Type: "item", Location: "🇵🇾 Paraguay"},
			{ID: 196, Type: "item", Location: "🇵🇪 Peru"},
			{ID: 197, Type: "item", Location: "🇵🇭 Philippines"},
			{ID: 198, Type: "item", Location: "🇵🇳 Pitcairn Island"},
			{ID: 199, Type: "item", Location: "🇵🇫 Polynesia"},
			{ID: 200, Type: "item", Location: "🇵🇷 Puerto Rico"},
			{ID: 201, Type: "item", Location: "🇶🇦 Qatar"},
			{ID: 202, Type: "item", Location: "🇷🇪 Reunion"},
			{ID: 203, Type: "item", Location: "🇷🇴 Romania"},
			{ID: 204, Type: "item", Location: "🇷🇼 Rwanda"},
			{ID: 205, Type: "item", Location: "🇸🇭 Saint Helena"},
			{ID: 206, Type: "item", Location: "🇰🇳 Saint Kitts and Nevis"},
			{ID: 207, Type: "item", Location: "🇱🇨 Saint Lucia"},
			{ID: 208, Type: "item", Location: "🇵🇲 Saint Pierre and Miquelon"},
			{ID: 209, Type: "item", Location: "🇻🇨 Saint Vincent and the Grenadines"},
			{ID: 210, Type: "item", Location: "🇼🇸 Samoa"},
			{ID: 211, Type: "item", Location: "🇸🇲 San Marino"},
			{ID: 212, Type: "item", Location: "🇸🇹 Sao Tome and Principe"},
			{ID: 213, Type: "item", Location: "🇸🇦 Saudi Arabia"},
			{ID: 214, Type: "item", Location: "🇸🇳 Senegal"},
			{ID: 215, Type: "item", Location: "🇷🇸 Serbia"},
			{ID: 216, Type: "item", Location: "🇸🇨 Seychelles"},
			{ID: 217, Type: "item", Location: "🇸🇱 Sierra Leone"},
			{ID: 218, Type: "item", Location: "🇲🇫 Saint-Martin"},
			{ID: 219, Type: "item", Location: "🇸🇽 Sint Maarten"},
			{ID: 220, Type: "item", Location: "🇸🇰 Slovakia"},
			{ID: 221, Type: "item", Location: "🇸🇮 Slovenia"},
			{ID: 222, Type: "item", Location: "🇸🇧 Solomon Islands"},
			{ID: 223, Type: "item", Location: "🇸🇴 Somalia"},
			{ID: 224, Type: "item", Location: "🇿🇦 South Africa"},
			{ID: 225, Type: "item", Location: "🇬🇸 South Georgia and the South Sandwich Islands"},
			{ID: 226, Type: "item", Location: "🇸🇸 South Sudan"},
			{ID: 227, Type: "item", Location: "🇱🇰 Sri Lanka"},
			{ID: 228, Type: "item", Location: "🇸🇩 Sudan"},
			{ID: 229, Type: "item", Location: "🇸🇷 Suriname"},
			{ID: 230, Type: "item", Location: "🇸🇯 Svalbard and Jan Mayen Islands"},
			{ID: 231, Type: "item", Location: "🇸🇿 Swaziland"},
			{ID: 232, Type: "item", Location: "🇨🇭 Switzerland"},
			{ID: 233, Type: "item", Location: "🇸🇾 Syria"},
			{ID: 234, Type: "item", Location: "🇹🇼 Taiwan"},
			{ID: 235, Type: "item", Location: "🇹🇯 Tajikistan"},
			{ID: 236, Type: "item", Location: "🇹🇿 Tanzania"},
			{ID: 237, Type: "item", Location: "🇹🇬 Togo"},
			{ID: 238, Type: "item", Location: "🇹🇰 Tokelau"},
			{ID: 239, Type: "item", Location: "🇹🇴 Tonga"},
			{ID: 240, Type: "item", Location: "🇹🇹 Trinidad and Tobago"},
			{ID: 241, Type: "item", Location: "🇹🇳 Tunisia"},
			{ID: 242, Type: "item", Location: "🇹🇷 Turkey"},
			{ID: 243, Type: "item", Location: "🇹🇲 Turkmenistan"},
			{ID: 244, Type: "item", Location: "🇹🇨 Turks and Caicos Islands"},
			{ID: 245, Type: "item", Location: "🇹🇻 Tuvalu"},
			{ID: 246, Type: "item", Location: "🇺🇬 Uganda"},
			{ID: 247, Type: "item", Location: "🇺🇾 Uruguay"},
			{ID: 248, Type: "item", Location: "🏝 Hawaii"},
			{ID: 249, Type: "item", Location: "🇺🇲 USA Minor Outlying Islands"},
			{ID: 250, Type: "item", Location: "🇺🇿 Uzbekistan"},
			{ID: 251, Type: "item", Location: "🇻🇺 Vanuatu"},
			{ID: 252, Type: "item", Location: "🇻🇦 Vatican City"},
			{ID: 253, Type: "item", Location: "🇻🇪 Venezuela"},
			{ID: 254, Type: "item", Location: "🇻🇳 Vietnam"},
			{ID: 255, Type: "item", Location: "🇻🇬 British Virgin Islands"},
			{ID: 256, Type: "item", Location: "🇻🇮 United States Virgin Islands"},
			{ID: 257, Type: "item", Location: "🇼🇫 Wallis and Futuna Islands"},
			{ID: 258, Type: "item", Location: "🇪🇭 Western Sahara"},
			{ID: 259, Type: "item", Location: "🇾🇪 Yemen"},
			{ID: 260, Type: "item", Location: "🇿🇲 Zambia"},
			{ID: 261, Type: "item", Location: "🇿🇼 Zimbabwe"},
		},
	}
}

func (l *locationData) GetAll() []models.LocationData {
	return l.items
}
